version: 2.1

jobs:
  build-frontend:
   docker:
       - image: jruby:9.3
   steps:
      cd frontend
      npm install
      npm run build
workflows:
  my_workflow:
    jobs:
      - build-frontend
