version: 2.1
jobs:
 build-frondend:
  docker:
  - image: circleci/node:13.8.0
  steps:
      - cd frontend
      - npm install
      - npm run build
      
 build-backend:
  docker:
       - image: circleci/node:13.8.0
  steps:
      - cd backend
      - npm install
      - npm run build
workflow:
 mywork-flow:
  jobs:
   -build-frontend
   -build-backend
