version: 2.1

jobs:
  build-frontend:
   docker:
       - image: jruby:9.3
    steps:
      - cd frontend
      - checkout
      - run: npm i
      - run: npm run lint
workflows:
  my_workflow:
    jobs:
      - build-frontend
