version: 2.1

jobs:
  build-frontend:
   docker:
       - image: jruby:9.3
   steps:
       - checkout
       - restore_cache:
          keys: [frontend-build]
       - run:
          name: Lint frontend
          command: |
           cd frontend
           npm install
           npm run build
workflows:
  my_workflow:
    jobs:
      - build-frontend
